### ISSUE TITLE
Feature request: display album tags and price from collection page

### ISSUE THREAD

**Issue by sergioenriquez** [borbiuk/band-play#1]
I am not sure if the Bandcamp API supports this, but it would convenient if one could also view the genre and price for each album while browsing a fan's collection page.

**Comment by borbiuk** [comment]
@sergioenriquez, hello!

That's a good idea, I'll look into a solution and let you know if I find anything.

Thank you for your activity!

**Comment by borbiuk** [comment]
@sergioenriquez I looked at the [Bandcamp documentation](https://bandcamp.com/developer), unfortunately, they do not provide such functionality.
