### ISSUE TITLE
Feature Request: Track Looping

### ISSUE THREAD

**Issue by SushiNebula** [borbiuk/band-play#10]
One feature I'm struggling to find with just about any BC extension is the ability to loop tracks, would it be possible to implement it here?

**Comment by borbiuk** [comment]
Hello. Yes, it is possible. Will be added soon

**Comment by borbiuk** [comment]
Version `6.0.4` has already been released. Please check a new `V` shortcut:
<img width="265" alt="image" src="https://github.com/user-attachments/assets/cd99801b-03a0-4591-8031-20559c8ef85e" />
