### ISSUE TITLE
Playing next track not working on discover

### ISSUE THREAD

**Issue by inverse** [borbiuk/band-play#6]
Just installed the extension and navigated to https://bandcamp.com/discover/electronic?loc=2950159 expedning it to play the next track. However when the track that's playing is finished it doesn't work and shows an error in the browser console

```
TypeError: Cannot read properties of null (reading 'parentElement')
    at F.playNextTrack (content.js:1:37339)
    at F.tryAutoplay (content.js:1:38027)
    at content.js:1:42733
(anonymous) @ content.js:1
setInterval
registerAutoplay @ content.js:1
(anonymous) @ content.js:1
i @ content.js:1
Promise.then
l @ content.js:1
(anonymous) @ content.js:1
L @ content.js:1
startAsync @ content.js:1
start @ content.js:1
117 @ content.js:1
r @ content.js:1
(anonymous) @ content.js:1
r.O @ content.js:1
(anonymous) @ content.js:1
(anonymous) @ content.js:1
Show 15 more frames
Show less
```

Let me know if you need anymore info

**Comment by borbiuk** [comment]
Hi there. I will check. Thanks

**Comment by borbiuk** [comment]
I fixed a few issues with the Discover page, it was related to changes by the Bandcamp team. Unfortunately, playback control is not available for now as DOM didn't contain the `<audio>` element, so I need time to investigate.

Version 5.1.3 will be available in the Chrom Web Store soon.

Available features are displayed in a guide:
![image](https://github.com/user-attachments/assets/1a9b7948-e86f-498e-ae6e-8f6b1314c9a5)
