### ISSUE TITLE
How to change keybinds?

### ISSUE THREAD

**Issue by romseguy** [borbiuk/band-play#7]
Hello, I'm using Vimium extension so there are conflicts with the default keybinds you defined, how do I change them? Thanks for your work!

**Comment by borbiuk** [comment]
Hi, thanks for bringing this up! Currently, there's no option to change the shortcuts, but it's a great idea to improve this feature. I'll try to find some time to address it soon.

**Comment by borbiuk** [comment]
I researched. The difficulty is that the Chrome Manifest V3 supports only 4 shortcuts. Need to implement the shortcut update mechanism and store new values ​​for the next session yourself.

**Comment by borbiuk** [comment]
Hi there. Custom shortcuts feature is available in v6.0.0. Check updates for the next 2 days. I'm waiting for feedback. Thanks
