### ISSUE TITLE
Discover page arrows does not change track timecode by a step. `movePlayback`

### ISSUE THREAD

**Issue by OlehPetrykUA** [borbiuk/band-play#8]

**Comment by borbiuk** [comment]
Hey! Thanks for reporting the issue.

For me, it works fine, so I’d need a bit more info to figure out what’s going wrong on your end:

1. **Operating system:** What OS are you using (Windows, macOS, Linux)?
2. **Other extensions:** Do you have any other extensions installed that might be capturing hotkeys?
3. **Debugging:** If possible, could you run the extension locally in developer mode and check the console for any errors or weird behavior? Sharing those logs would really help. I can help u with debug and installation.
