### ISSUE TITLE
BandPlay No Longer Working on Brave Browser

### ISSUE THREAD

**Issue by femto821** [borbiuk/band-play#9]
The BandPlay extension has stopped working for me as of yesterday 11/23/24. I tried disabling other extensions to make sure there wasn't a conflict, but it didn't help.

Brave Version: 1.57.64 Chromium: 116.0.5845.188 (Official Build) (x86_64)
Operating System: macOS 10.14.6

**Comment by borbiuk** [comment]
Hi there. I have a bug in the `6.0.0` version. Please wait for when `6.0.1` will be released (I'm awaiting approval from Google now). Let me know if all is ok after the `6.0.1` check

**Comment by femto821** [comment]
Hi! Thank you for replying so quickly. Okay, I will wait for the next
update. Will the update happen automatically or do I need to check for it
and install it manually?

**Comment by borbiuk** [comment]
You can open the "Extensions" tab in the browser menu and see the installed version of Band Play. If the version currently installed is 6.0.0, then this is the problem I think. This means that your extensions are updated automatically. In any case, I will write back about the available update

**Comment by femto821** [comment]
Okay, I just checked and it's like you said. My installed BandPlay version
is 6.0.0. So the updates are happening automatically. I will wait for the
6.0.1 update. I hope you can let me know when it's available so I can know
to test if it's working.

**Comment by borbiuk** [comment]
6.0.1 is released

**Comment by femto821** [comment]
Hi! I installed it. Everything is working now. Thank you!! :)
